---
- name: "Install RPM non-free"
  dnf:
    name: https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ansible_facts['distribution_major_version']}}.noarch.rpm
    state: latest
  become: true

- name: "Install RPM free"
  dnf:
    name: https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ansible_facts['distribution_major_version']}}.noarch.rpm
    state: latest
  become: true
