---
- hosts: localhost
  remote_user: nguyenvinhlinh

  become_method: sudo
  tasks:
    - name: "1. Ping server"
      ping:
        data: pong
    - name: "2. Update fedora"
      dnf:
        name: "*"
        state: latest
      become: yes
    - name: "3. Install zsh"
      dnf:
        name: zsh
        state: latest
      become: yes
    - name: "4. Install emacs"
      dnf:
        name: emacs
        state: latest
      become: yes
    - name: "5. Install git"
      dnf:
        name: git
        state: latest
      become: yes
    - name: "6. Install gnome-tweaks"
      dnf:
        name: gnome-tweaks
        state: latest
      become: yes
    - name: "7. Install RPM Fusion"
      include_role:
        name: robertdebock.rpmfusion
        apply:
          become: true
    - name: "8. Install Google Chrome"
      dnf:
        name: "https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm"
        state: latest
      become: yes
    - name: "10. Install MPV"
      dnf:
        name: "mpv"
        state: latest
      become: yes
    - name: "11. Install DBeaver"
      dnf:
        name: "https://dbeaver.io/files/dbeaver-ce-latest-stable.x86_64.rpm"
        state: latest
        disable_gpg_check: yes
      become: yes
    - name: "12. Install oh-my-zsh"
      include_role:
        name: gantsign.oh-my-zsh
      vars:
        users:
          - username: nguyenvinhlinh
            oh_my_zsh:
              theme: robbyrussell
              plugins:
                - git
          - username: root
            oh_my_zsh:
              theme: darkblood
              plugins:
                - git
    - name: "13. Clone .emacs.d"
      ansible.builtin.git:
        repo: git@github.com:nguyenvinhlinh/emacs.d.git
        dest: /home/nguyenvinhlinh/.emacs.d
        version: master
    - name: "14. Install Steam"
      dnf:
        name: "steam"
        state: latest
      become: yes
    - name: "15. Install Libreoffice"
      dnf:
        name: libreoffice
        state: latest
      become: yes
    - name: "16. Install Postman"
      include_role:
        name: postman
    - name: "17. Install Microsoft Teams"
      dnf:
        name: https://packages.microsoft.com/yumrepos/ms-teams/teams-1.5.00.23861-1.x86_64.rpm
        state: present
        disable_gpg_check: true
      become: yes
    - name: "18. Install Skype"
      dnf:
        name: https://repo.skype.com/latest/skypeforlinux-64.rpm
        state: present
        disable_gpg_check: true
      become: yes
    - name: "19. Install Discord"
      include_role:
        name: discord
    - name: "20. Add flathub repo"
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
      become: yes
    - name: "21. Install gnome shell extension manager"
      community.general.flatpak:
        name: org.gnome.Extensions
        state: present
        remote: flathub
    - name: "22. Install FreeCAD"
      dnf:
        name: freecad
        state: latest
      become: yes

    - name: "23. Install Drawing"
      dnf:
        name: drawing
        state: latest
      become: yes
