---
- hosts: workstation
  remote_user: nguyenvinhlinh

  become_method: sudo
  tasks:
    - name: "1. Ping server"
      ping:
        data: pong
    - name: "2. Update fedora"
      dnf:
        name: "*"
        state: latest
      become: yes
    - name: "3. Install zsh"
      dnf:
        name: zsh
        state: latest
      become: yes
    - name: "4. Install emacs"
      dnf:
        name: emacs
        state: latest
      become: yes
    - name: "5. Install git"
      dnf:
        name: git
        state: latest
      become: yes
    - name: "6. Install Dropbox"
      include_role:
        name: dropbox
    - name: "7. Install RPM Fusion"
      include_role:
        name: "rpm-fusion"
    - name: "8. Install Google Chrome"
      dnf:
        name: "https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm"
        state: latest
      become: yes
    - name: "9. Install Postman"
      include_role:
        name: postman
    - name: "10. Install MPV"
      dnf:
        name: "mpv"
        state: latest
      become: yes
    - name: "11. Install DBeaver"
      dnf:
        name: "https://dbeaver.io/files/dbeaver-ce-latest-stable.x86_64.rpm"
        state: latest
      become: yes
