---
- hosts: localhost
  remote_user: nguyenvinhlinh

  become_method: sudo
  tasks:
    - name: "1. Ping server"
      ping:
        data: pong
    - name: "2. Update fedora"
      dnf:
        name: "*"
        state: latest
      become: yes
    - name: "3. Install zsh"
      dnf:
        name: zsh
        state: latest
      become: yes
    - name: "4. Install emacs"
      dnf:
        name: emacs
        state: latest
      become: yes
    - name: "5. Install git"
      dnf:
        name: git
        state: latest
      become: yes
    - name: "6. Install gnome-tweaks"
      dnf:
        name: gnome-tweaks
        state: latest
      become: yes
    - name: "7. Install RPM Fusion"
      include_role:
        name: robertdebock.rpmfusion
        apply:
          become: true
    - name: "8. Install Google Chrome"
      dnf:
        name: "https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm"
        state: latest
      become: yes
    - name: "10. Install MPV"
      dnf:
        name: "mpv"
        state: latest
      become: yes
    - name: "11. Install DBeaver"
      dnf:
        name: "https://dbeaver.io/files/dbeaver-ce-latest-stable.x86_64.rpm"
        state: latest
        disable_gpg_check: yes
      become: yes
    - name: "12. Install oh-my-zsh"
      include_role:
        name: gantsign.oh-my-zsh
      vars:
        users:
          - username: nguyenvinhlinh
            oh_my_zsh:
              theme: robbyrussell
              plugins:
                - git
    - name: "13. Clone .emacs.d"
      ansible.builtin.git:
        repo: git@github.com:nguyenvinhlinh/emacs.d.git
        dest: /home/nguyenvinhlinh/.emacs.d
        version: master
    - name: "14. Install Steam"
      dnf:
        name: "steam"
        state: latest
      become: yes
